In [4]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [6]:
df = pd.read_csv('Temperature-Revenue model devtown machine learning.csv')

In [7]:
df.head()

Temperature     Revenue
0    24.566884  534.799028
1    26.005191  625.190122
2    27.790554  660.632289
3    20.595335  487.706960
4    11.503498  316.240194

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Temperature  500 non-null    float64
 1   Revenue      500 non-null    float64
dtypes: float64(2)
memory usage: 7.9 KB


In [9]:
x = df['Temperature']
y = df['Revenue']

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [12]:
len(x_train)

400

In [13]:
len(x_test)

100

In [14]:
model = LinearRegression()

In [15]:
y_test.ndim

1

In [16]:
x_test.ndim

1

In [17]:
np.array([x_train]).ndim

2

In [20]:
dim = np.array([x_train]).ndim

In [22]:
model.fit(np.array([x_train]).reshape(-1,1), y_train)

LinearRegression()

In [24]:
y_pred = model.predict(np.array(x_test).reshape(-1,1))

In [25]:
y_pred

array([593.08480099, 197.21419583, 441.37796121, 347.50681196,
       682.53090818, 495.96572042, 307.93250566, 454.91109034,
       671.08062423, 746.87623159, 564.94956535, 722.48503968,
       662.60367507, 508.50580479, 394.52231673, 284.56425598,
       900.19192077, 622.98210737, 382.79938559, 566.40745118,
       509.99223758, 864.25742416, 396.7952386 ,  44.66099933,
       417.28688856, 683.59781153, 652.05615132, 652.84329032,
       364.40544228, 321.58104843, 706.47301253, 563.73825581,
       591.91339873, 443.41654734, 415.1716205 , 359.87599918,
       664.00074795, 541.61054689, 473.45176285, 639.79413094,
       583.74528996, 636.4793013 , 576.14298029, 312.16199542,
       561.97133813, 351.31737176, 690.31307651, 479.24436004,
       724.40551783, 314.49245015, 559.01499767, 745.08352761,
       659.57923109, 436.01389535, 330.16703093, 181.89647513,
       602.63172239, 695.66274408, 655.5086557 , 255.273976  ,
       639.31463166, 456.6560575 , 530.15565768, 741.48

In [26]:
r2_score(y_test, y_pred)

0.9779094774322878

In [27]:
model.predict([[1]])

array([66.12471928])

In [28]:
model.predict([[30]])

array([688.57259763])

In [30]:
import pickle

In [33]:
with open('model.pkl','wb') as files:
    pickle.dump(model,files)
     